theme: jekyll-theme-slate
title: Hartl.Bene Software
description: AI Consulting, Scientific Research and Prototyping
show_toplinks: true
github:
  is_project_page: true
  repository_url: https://github.com/bhartl
  owner_url: https://github.com/bhartl/bhartl.github.io
  owner_name: B. Hartl
  education_url: /edu
  projects_url: /pro
  skills_url: /lan
  experience_url: /work
  bib_url: /ref
