theme: jekyll-theme-slate
title: Ben Hartl, PhD
description: Scientific Research, Software Engineering, AI
show_toplinks: true
github:
  is_project_page: true
  repository_url: https://github.com/bhartl
  owner_url: https://github.com/bhartl/bhartl.github.io
  owner_name: B. Hartl
  education_url: /edu
  projects_url: /pro
  skills_url: /skill
  experience_url: /work
  bib_url: /bib
  cv_url: /cv
