theme: jekyll-theme-slate
title: Hartl.Bene Programming
description: AI Consulting, Scientific Research and Prototyping
github:
  # zip_url: http://example.com/download.zip
  LinkedIn: https://www.linkedin.com/in/bhartl/
  TU-Wien: http://smt.tuwien.ac.at/people/hartl/
